// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ZvBSqQ9U3g83ZIvjUZTTBOd1IELRWh0',
    appId: '1:895734210430:web:2e15237d20283487899d2f',
    messagingSenderId: '895734210430',
    projectId: 'yt-recreation',
    authDomain: 'yt-recreation.firebaseapp.com',
    storageBucket: 'yt-recreation.appspot.com',
    measurementId: 'G-R14RMXMQFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr54LDn0CH3FU79WcST1ueQLorQu57lW0',
    appId: '1:895734210430:android:4645e0a9cad39f60899d2f',
    messagingSenderId: '895734210430',
    projectId: 'yt-recreation',
    storageBucket: 'yt-recreation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuidplbQLoKWenzNkC1LBGBRF3o05PqW8',
    appId: '1:895734210430:ios:f0798dcb7e7398c4899d2f',
    messagingSenderId: '895734210430',
    projectId: 'yt-recreation',
    storageBucket: 'yt-recreation.appspot.com',
    iosClientId: '895734210430-1t1fpc5n5vrmc1e35c39bnk43kfg9e1h.apps.googleusercontent.com',
    iosBundleId: 'site.ritom.youtube',
  );
}
